export default {
  products: [
    {
      _id: '1',
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 50,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 4,
        description: 'Shirt sits closer to the body for a slighly tight, fitted look.'
      
    },
    {
      _id: '2',
      name: 'Fitted Shirt',
      category: 'Shirts',
      image: '/images/d2.jpg',
      price: 70,
      brand: ' Nike',
      rating: 4.2,
      numReviews: 5,
      countInStock: 10,
    },
    {
      _id: '3',
      name: 'Cotton Shirt',
      category: 'Shirts',
      image: '/images/d3.jpg',
      price: 40,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '4',
      name: 'Classic Shirt',
      category: 'Shirt',
      image: '/images/d4.jpg',
      price: 45,
      brand: ' Nike',
      rating: 5.0,
      numReviews: 8,
      countInStock: 8,
    }, 
    {
      _id: '5',
      name: 'Tapered Pants',
      category: 'Pants',
      image: '/images/d5.jpg',
      price: 80,
      brand: ' Nike',
      rating: 5.0,
      numReviews: 8,
      countInStock: 7,
    }, 
    {
      _id: '6',
      name: 'Cotton Pants',
      category: 'Pants',
      image: '/images/d6.jpg',
      price: 65,
      brand: ' Nike',
      rating: 4.2,
      numReviews: 8,
      countInStock: 7,
    }, 
     {
      _id: '7',
      name: 'Slim Pants',
      category: 'Jackets',
      image: '/images/d7.jpg',
      price: 70,
      brand: ' Nike',
      rating: 4.8,
      numReviews: 8,
      countInStock: 8,
    }, 
    {
      _id: '8',
      name: 'Winter Jacket',
      category: 'Jackets',
      image: '/images/d8.jpg',
      price: 100,
      brand: ' Nike',
      rating: 4.7,
      numReviews: 8,
      countInStock: 6,
    }, 
    {
      _id: '9',
      name: 'Leather Jacket',
      category: 'Jackets',
      image: '/images/d9.jpg',
      price: 120,
      brand: ' Nike',
      rating: 5.0,
      numReviews: 8,
      countInStock: 4,
    }, 
    {
      _id: '10',
      name: 'Denim Jacket',
      category: 'Jackets',
      image: '/images/d10.jpg',
      price: 85,
      brand: ' Nike',
      rating: 4.6,
      numReviews: 8,
      countInStock: 3,
    }, 
    
  ]
}